version: '2'
services:
  hypnos:
    build: .
    ports:
      - "5002:5002"
    networks:
      - hypnos_network
  ccnlp:
    image: nlpbox/corenlp
    networks:
     - hypnos_network
    command: ["java", "-mx4g", "-cp", "*", "edu.stanford.nlp.pipeline.StanfordCoreNLPServer", "-port", "5000"]
    ports:
     - "5000:5000"
  petrarch:
    build: petrarch/.
    ports: 
        - "5001:5001"
    networks:
      - hypnos_network

networks:
  hypnos_network:
    driver: bridge
